AllCops:
  Exclude:
    - "db/**/**"
    - "docs/**/**"
    - "specific-views-images/**/**"
    - "specific-views-pdf/**/**"
    - "vendor/**/**"
    - "bin/**/**"
    - "tmp/**/**"
    - "node_modules/**/**"
    - "config/**/**"
    - "Guardfile"
    - "app/docs/**"
Metrics/ClassLength:
  Exclude:
    - "test/**/**"
Layout/LineLength:
  Max: 120
  Exclude:
    - "test/**/**"
Metrics/MethodLength:
  Max: 15
Style/SignalException:
  Exclude:
    - "app/concepts/operations/**/**"
Lint/UnreachableCode:
  Exclude:
    - "app/concepts/operations/**/**"
Metrics/ParameterLists:
  Exclude:
    - "app/errors/**"