---
swagger: '2.0'
info:
  title: Rswag Example REST API
  version: 1.0.0
  description: Rswag Example REST API
host: ''
basePath: "/"
paths: {}
securityDefinitions:
  Bearer:
    description: "..."
    type: apiKey
    name: Authorization
    in: header
schemes:
- http
- https
consumes:
- application/json
